<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Run on Firefox"
           tests="2"
           failures="1"
           errors="0"
           skipped="0"
           time="4.743">
  <properties />
            <testcase name="User_02_Login" time="1.401" classname="com.nopcommerce.user.Level_15_Extend_Screenshort">
                <failure type="java.lang.AssertionError"
                  message="expected [false] but found [true]"
              >
<![CDATA[java.lang.AssertionError: expected [false] but found [true]
  org.testng.Assert.fail(Assert.java:111)
  org.testng.Assert.failNotEquals(Assert.java:1578)
  org.testng.Assert.assertFalse(Assert.java:79)
  org.testng.Assert.assertFalse(Assert.java:89)
  com.nopcommerce.user.Level_15_Extend_Screenshort.User_02_Login(Level_15_Extend_Screenshort.java:82)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:568)
  org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
  org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
  org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
  org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
  org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
  org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
  org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
  org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
  java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
  org.testng.TestRunner.privateRun(TestRunner.java:848)
  org.testng.TestRunner.run(TestRunner.java:621)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
  org.testng.SuiteRunner.run(SuiteRunner.java:336)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
  org.testng.TestNG.runSuites(TestNG.java:1114)
  org.testng.TestNG.run(TestNG.java:1082)
  com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:65)
  com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="User_01_Register" time="3.342" classname="com.nopcommerce.user.Level_15_Extend_Screenshort" />
      
</testsuite>
